last_change = 2026-08-28T12:19:19.294617Z
addr = 0x9f2d0
size = 0x46
name = "CEngineServer_ClientPrintf"
type = "void"

[header]
name = "CEngineServer_ClientPrintf"
addr = 0x9f2d0
type = "void"

[header.args]
