last_change = 2026-08-28T12:19:16.509958Z
addr = 0x9aeb0
size = 0x11f
name = "CNetworkGameServerBase_SetMaxClients"

[header]
name = "CNetworkGameServerBase_SetMaxClients"
addr = 0x9aeb0

[header.args]
