last_change = 2026-08-28T12:19:19.522519Z
addr = 0xabab0
size = 0x48c
name = "CNetworkGameServerBase_Init"
type = "long long"

[header]
name = "CNetworkGameServerBase_Init"
addr = 0xabab0
type = "long long"

[header.args]
