last_change = 2026-08-28T12:19:16.510267Z
addr = 0x1d2890
size = 0x15d
name = "CNetworkClientService_OnFrameBoundary"

[header]
name = "CNetworkClientService_OnFrameBoundary"
addr = 0x1d2890

[header.args]
