last_change = 2026-08-28T12:19:20.532392Z
addr = 0x1dc6c0
size = 0xc7b
name = "CNetworkServerService_RegisterEventMapInternal"

[header]
name = "CNetworkServerService_RegisterEventMapInternal"
addr = 0x1dc6c0

[header.args]
