last_change = 2026-08-28T12:19:20.732986Z
addr = 0x20e9f0
size = 0xb6
name = "CEngineServiceMgr_Shutdown"
type = "void"

[header]
name = "CEngineServiceMgr_Shutdown"
addr = 0x20e9f0
type = "void"

[header.args]
