last_change = 2026-08-28T12:19:20.852167Z
addr = 0x21b3f0
size = 0x29c
name = "CLoopTypeBase_GenerateSecondaryDependencies"

[header]
name = "CLoopTypeBase_GenerateSecondaryDependencies"
addr = 0x21b3f0

[header.args]
