last_change = 2026-08-28T12:19:20.843258Z
addr = 0x21b160
size = 0x283
name = "CLoopTypeBase_GenerateServiceDependencies"

[header]
name = "CLoopTypeBase_GenerateServiceDependencies"
addr = 0x21b160

[header.args]
